#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow"]
# ///
"""Export a few render set 3 hard negatives for the page, and the set 3 counts.

Set 3 is a render set that swaps in leaves with another disease and an orange rim around the dark lesion, so the
model stops reading orange as rust (see data/synthetic/README.md, "v3: orange is not always rust").
Runs on it are in runs/*-v3_*. This script only copies six pictures and counts rows.

  uv run presentation-v2/tools/build_v3.py

Writes presentation-v2/img/v3/*.webp and presentation-v2/src/data/v3.js.
"""
import csv
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "presentation-v2"
OUT = SITE / "img" / "v3"
PICKS = ["v3_260_r0_closeup_0", "v3_1163_r0_closeup_0", "v3_574_r0_closeup_0", "v3_1064_r0_closeup_0", "v3_227_r0_closeup_0", "v3_514_r0_closeup_0"]


def main():
    v1 = {r["id"] for r in csv.DictReader(open(ROOT / "data/synthetic/v1/manifest.csv"))}
    rows = list(csv.DictReader(open(ROOT / "data/synthetic/v3/manifest.csv")))
    new = [r for r in rows if r["id"] not in v1]
    by = {r["id"]: r for r in rows}
    OUT.mkdir(parents=True, exist_ok=True)
    files = []
    for pid in PICKS:
        r = by[pid]
        assert r["rust"] == "0" and r["id"] not in v1, f"{pid} is not a new no-rust render"
        im = Image.open(ROOT / r["image"]).convert("RGB")
        im.thumbnail((420, 420), Image.LANCZOS)
        dst = OUT / f"{pid}.webp"
        im.save(dst, "WEBP", quality=82, method=6)
        files.append({"id": pid, "file": f"img/v3/{pid}.webp", "sourceId": int(r["source_id"]), "preset": r["preset"], "group": r["group"], "w": im.size[0], "h": im.size[1]})
    data = {
        "total": len(rows),
        "copiedFromV1": len(rows) - len(new),
        "newHardNegatives": len(new),
        "rustPainted": 0,
        "pictures": files,
    }
    (SITE / "src" / "data" / "v3.js").write_text(
        "// generated by tools/build_v3.py, do not edit\n\nexport const V3 = " + json.dumps(data, indent=1) + ";\n", encoding="utf-8")
    print(f"v3: {data['total']} rows, {data['copiedFromV1']} copied from v1, {data['newHardNegatives']} new hard negatives; wrote {len(files)} pictures")


if __name__ == "__main__":
    main()
