#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow", "numpy"]
# ///
"""Pick the real Uganda photos where the 3D-trained versions and the real-only version disagree, in all three seeds.

  uv run --script presentation-v2/tools/build_why.py

Reads runs/*/scores_field_uganda_all.csv and each run's threshold in metrics.json (the cut-off from BRACOL validation).
Writes img/why/*.webp (256 px, no resize, no EXIF) and src/data/why.js. Nothing is trained or scored here.

Set 4 is only counted in "fixed" (the photo no longer gets a rust answer). Two groups, each found by the same rule: the answer of the 3D versions is the same in all 6 runs (rendered only and
rendered + real, seeds 0 to 2, set 1), the answer of the real-only version is the opposite in all 3 runs, and the call is made at each run's own cut-off.
  other: phoma photos (no rust) that the 3D versions call rust and the real-only version calls no rust.
  rust:  rust photos that the 3D versions call rust and the real-only version misses.
We show the five with the widest gap. A photo with black bars is skipped.
"""
import csv
import io
import json
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE.parent
ROOT = OUT.parent
RUNS = ROOT / "runs"
IMG = OUT / "img" / "why"
SEEDS = (0, 1, 2)
SETS = {
    "real": [f"real_d140_f100_s{s}" for s in SEEDS],
    "mix": [f"mix_d140_f100_s{s}" for s in SEEDS],
    "syn": [f"syn_d140_f0_s{s}" for s in SEEDS],
    "mix3": [f"mix-v3_d140_f100_s{s}" for s in SEEDS],
    # set 4 (set 1 plus the look-alikes): the seeds that exist
    "mix4": [f"mix-combo_d140_f100_s{s}" for s in SEEDS if (RUNS / f"mix-combo_d140_f100_s{s}" / "scores_field_uganda_all.csv").exists()],
}
SHOW = 5


def load(name):
    m = json.loads((RUNS / name / "metrics.json").read_text())
    thr = m["threshold_from_val"]
    rows = {}
    with open(RUNS / name / "scores_field_uganda_all.csv", newline="") as f:
        for r in csv.DictReader(f):
            rows[r["id"]] = (int(r["rust"]), r["group"], float(r["score"]) - thr)
    return rows


def padded(path):
    with Image.open(path) as im:
        g = np.asarray(im.convert("L"))
    return int((g.max(axis=1) < 8).sum()) > 20 or int((g.max(axis=0) < 8).sum()) > 20


def main():
    data = {k: [load(n) for n in names] for k, names in SETS.items()}
    manifest = {r["id"]: r for r in csv.DictReader(open(ROOT / "data/field/uganda/manifest.csv", newline=""))}
    ids = list(data["real"][0])

    def calls(key, i):
        return {1 if d[i][2] > 0 else 0 for d in data[key]}

    found = {"other": [], "rust": []}
    for i in ids:
        truth, group, _ = data["real"][0][i]
        if calls("mix", i) != {1} or calls("syn", i) != {1} or calls("real", i) != {0}:
            continue
        gap = min(d[i][2] for d in data["mix"] + data["syn"]) - max(d[i][2] for d in data["real"])
        if group == "other":
            found["other"].append((gap, i, calls("mix3", i) == {0}, bool(data["mix4"]) and calls("mix4", i) == {0}))
        elif truth == 1:
            found["rust"].append((gap, i, None, None))
    out = {}
    IMG.mkdir(parents=True, exist_ok=True)
    keep = set()
    for kind, rows in found.items():
        rows.sort(key=lambda t: (-t[0], t[1]))
        pics = []
        for gap, i, _, _ in rows:
            if len(pics) == SHOW:
                break
            src = ROOT / manifest[i]["image"]
            if padded(src):
                continue
            rel = f"{kind}_{len(pics) + 1}_{i}.webp"
            with Image.open(src) as im:
                buf = io.BytesIO()
                im.convert("RGB").save(buf, "WEBP", quality=80, method=6)
            p = IMG / rel
            if not p.exists() or p.read_bytes() != buf.getvalue():
                p.write_bytes(buf.getvalue())
            keep.add(rel)
            pics.append({"id": i, "file": f"img/why/{rel}", "group": manifest[i]["group"], "gap": round(gap, 2)})
        out[kind] = {"count": len(rows), "pics": pics}
    out["other"]["v3Fixed"] = sum(1 for t in found["other"] if t[2])
    out["other"]["v4Fixed"] = sum(1 for t in found["other"] if t[3]) if data["mix4"] else None
    for stale in IMG.glob("*.webp"):
        if stale.name not in keep:
            stale.unlink()
    js = "// generated by tools/build_why.py, do not edit\nexport const WHY = " + json.dumps(out, indent=1) + ";\n"
    (OUT / "src/data/why.js").write_text(js)
    print(f"phoma called rust by the 3D versions only: {out['other']['count']} (set 3 fixes {out['other']['v3Fixed']}, set 4 fixes {out['other']['v4Fixed']}); rust found by the 3D versions only: {out['rust']['count']}")
    print("wrote", len(keep), "images and src/data/why.js")


if __name__ == "__main__":
    main()
