#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow"]
# ///
"""The four photos of the laptop demo, and what the demo model says about them.

  uv run --script presentation/site/tools/build_demo.py

The demo is `scripts/model/predict.py` with the adapter of run real_d140_f10_s0 (10% of the real photos). It reads the cut-off and the
"not sure" margin from runs/real_d140_f10_s0/field_calibration.json, which were set on 1,492 Uganda photos outside the 300 test photos.
This script does not run the model. It reads the scores the run already saved for the same photos (scores_field_uganda_all.csv),
applies the same rule as predict.py (not sure when the score is within the margin of the cut-off), and copies the four photos from
submission/demo_photos/. Writes img/demo/*.webp and src/data/demo.js.
"""
import csv
import io
import json
import re
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE.parent
ROOT = OUT.parent.parent
RUN = "real_d140_f10_s0"
ORDER = ["rust_yes", "no_rust", "not_sure_1", "not_sure_2"]  # the order of the video script


def verdict(score, cutoff, margin):
    if abs(score - cutoff) < margin:
        return "unsure"
    return "yes" if score >= cutoff else "no"


def main():
    run = ROOT / "runs" / RUN
    cal = json.loads((run / "field_calibration.json").read_text())
    scores = {}
    with open(run / "scores_field_uganda_all.csv", newline="") as f:
        for r in csv.DictReader(f):
            scores[r["id"]] = (int(r["rust"]), r["group"], float(r["score"]))
    pool = int(re.match(r"(\d+)", cal["set_on"]).group(1))
    files = {}
    for p in sorted((ROOT / "submission" / "demo_photos").glob("*.jpg")):
        m = re.match(r"(.+)_(fi_\d+)\.jpg$", p.name)
        files[m.group(1)] = (m.group(2), p)
    if sorted(files) != sorted(ORDER):
        raise SystemExit(f"demo photos are {sorted(files)}, expected {sorted(ORDER)}")
    (OUT / "img" / "demo").mkdir(parents=True, exist_ok=True)
    photos = []
    for kind in ORDER:
        pid, src = files[kind]
        rust, group, score = scores[pid]
        buf = io.BytesIO()
        Image.open(src).convert("RGB").save(buf, "WEBP", quality=84, method=6)
        dst = OUT / "img" / "demo" / f"{pid}.webp"
        if not dst.exists() or dst.read_bytes() != buf.getvalue():
            dst.write_bytes(buf.getvalue())
        photos.append({"id": pid, "file": f"img/demo/{pid}.webp", "kind": kind, "rust": rust, "group": group, "score": round(score, 2),
                       "verdict": verdict(score, cal["cutoff"], cal["margin"])})
    t = cal["on_the_300_test_photos"]
    data = {"run": RUN, "cutoff": cal["cutoff"], "margin": cal["margin"], "pool": pool, "test": {"n": 300, "accuracy": round(t["accuracy"], 4),
            "coverage": round(t["coverage"], 4), "answered": round(t["answered"], 4)}, "photos": photos}
    (OUT / "src" / "data" / "demo.js").write_text("// generated by tools/build_demo.py, do not edit\nexport const DEMO = " + json.dumps(data, indent=1) + ";\n")
    print("demo:", [(p["id"], p["verdict"]) for p in photos], "| 300 test photos:", data["test"])


if __name__ == "__main__":
    main()
