// Generated by tools/prepare_assets.py from presentation/site. Do not edit by hand.
// The numbers are the real log of each render (Blender job and phone effects), not made-up values.

export const LEAF = {
 "id": 897,
 "labels": {
  "rust": 1,
  "miner": 1,
  "phoma": 0,
  "cercospora": 0,
  "severity": 4
 },
 "textureW": 1566,
 "textureH": 587
};
export const LESIONS = {
 "orange": [
  [0.2661, 0.3893, 1575.13],
  [0.515, 0.3123, 1309.01],
  [0.6708, 0.5617, 456.15],
  [0.6124, 0.7941, 292.59],
  [0.7329, 0.3303, 91.05],
  [0.5253, 0.8004, 57.55],
  [0.8535, 0.5764, 15.38],
  [0.7869, 0.3336, 6.91]
 ],
 "brown": [
  [0.2621, 0.3844, 786.09]
 ]
};
export const PRESETS = [
 {
  "key": "overcast",
  "name": "Overcast",
  "raw": "leaf_overcast_raw",
  "phone": "leaf_overcast_phone",
  "meta": {
   "light": "overcast",
   "sky": "hdri:city",
   "exposure_ev": -0.74,
   "lens_mm": 28.3,
   "fstop": 2.9,
   "cam_tilt_deg": 3.1,
   "cam_dist_m": 0.149,
   "leaf_len_m": 0.144,
   "cover": 0.77,
   "render_s": 0.62,
   "seed": 814290349,
   "phone": {
    "exposure_gain": 2.57,
    "sat": 0.56,
    "noise": 0.0103,
    "jpeg_q": 67
   }
  }
 },
 {
  "key": "sun",
  "name": "Sun",
  "raw": "leaf_sun_raw",
  "phone": "leaf_sun_phone",
  "meta": {
   "light": "sun",
   "sun_el": 46.3,
   "sun_az": 39.0,
   "kelvin": 6028,
   "sun_energy": 4.09,
   "exposure_ev": -0.65,
   "lens_mm": 26.0,
   "fstop": 3.6,
   "cam_tilt_deg": 5.2,
   "cam_dist_m": 0.12,
   "leaf_len_m": 0.126,
   "cover": 0.78,
   "render_s": 0.82,
   "seed": 1142341918,
   "phone": {
    "exposure_gain": 1.56,
    "mood_t": -0.185,
    "sat": 1.2,
    "jpeg_q": 78
   }
  }
 },
 {
  "key": "golden",
  "name": "Golden hour",
  "raw": "leaf_golden_raw",
  "phone": "leaf_golden_phone",
  "meta": {
   "light": "golden",
   "sun_el": 6.3,
   "sun_az": 39.0,
   "kelvin": 3645,
   "sun_energy": 3.32,
   "exposure_ev": 0.6,
   "lens_mm": 26.0,
   "fstop": 3.6,
   "cam_tilt_deg": 5.2,
   "cam_dist_m": 0.12,
   "leaf_len_m": 0.126,
   "cover": 0.78,
   "render_s": 0.91,
   "seed": 1142341918,
   "phone": {
    "exposure_gain": 1.23,
    "mood_t": 0.056,
    "sat": 1.14,
    "motion_px": 7,
    "jpeg_q": 56
   }
  }
 },
 {
  "key": "shade",
  "name": "Shade",
  "raw": "leaf_shade_raw",
  "phone": "leaf_shade_phone",
  "meta": {
   "light": "shade",
   "sky": "hdri:forest",
   "exposure_ev": 1.8,
   "lens_mm": 27.3,
   "fstop": 2.3,
   "cam_tilt_deg": 5.3,
   "cam_dist_m": 0.156,
   "leaf_len_m": 0.147,
   "cover": 0.74,
   "render_s": 0.6,
   "seed": 1750599284,
   "phone": {
    "exposure_gain": 1.12,
    "mood_t": -0.143,
    "sat": 1.16,
    "noise": 0.0108,
    "jpeg_q": 67
   }
  }
 },
 {
  "key": "backlit",
  "name": "Backlit",
  "raw": "leaf_backlit_raw",
  "phone": "leaf_backlit_phone",
  "meta": {
   "light": "backlit",
   "sun_el": 24.0,
   "sun_az": 39.0,
   "kelvin": 5793,
   "sun_energy": 4.09,
   "exposure_ev": -0.24,
   "lens_mm": 26.0,
   "fstop": 3.6,
   "cam_tilt_deg": 4.1,
   "cam_dist_m": 0.12,
   "leaf_len_m": 0.126,
   "cover": 0.78,
   "render_s": 1.21,
   "seed": 1142341918,
   "phone": {
    "exposure_gain": 1.11,
    "mood_t": 0.093,
    "sat": 0.69,
    "noise": 0.0068,
    "jpeg_q": 70
   }
  }
 },
 {
  "key": "rain",
  "name": "Rain",
  "raw": "leaf_rain_raw",
  "phone": "leaf_rain_phone",
  "meta": {
   "light": "overcast",
   "sky": "hdri:city",
   "exposure_ev": 0.38,
   "lens_mm": 28.3,
   "fstop": 2.9,
   "cam_tilt_deg": 3.1,
   "cam_dist_m": 0.148,
   "leaf_len_m": 0.144,
   "cover": 0.78,
   "render_s": 0.88,
   "seed": 814290349,
   "phone": {
    "exposure_gain": 0.95,
    "mood_t": -0.125,
    "sat": 0.79,
    "jpeg_q": 57
   }
  }
 },
 {
  "key": "sun_wet",
  "name": "After rain",
  "raw": "leaf_sun_wet_raw",
  "phone": "leaf_sun_wet_phone",
  "meta": {
   "light": "sun",
   "sun_el": 79.2,
   "sun_az": 199.6,
   "kelvin": 5538,
   "sun_energy": 4.54,
   "exposure_ev": -1.02,
   "lens_mm": 25.6,
   "fstop": 3.9,
   "cam_tilt_deg": 4.4,
   "cam_dist_m": 0.147,
   "leaf_len_m": 0.162,
   "cover": 0.79,
   "render_s": 2.77,
   "seed": 618255686,
   "phone": {
    "exposure_gain": 1.23,
    "mood_t": -0.097,
    "sat": 1.05,
    "blur_sigma": 1.04,
    "noise": 0.0031,
    "jpeg_q": 94
   }
  }
 },
 {
  "key": "studio",
  "name": "Studio",
  "raw": "leaf_studio_raw",
  "phone": "leaf_studio_phone",
  "meta": {
   "light": "studio",
   "sky": "flat",
   "exposure_ev": 0.55,
   "lens_mm": 26.6,
   "fstop": 3.0,
   "cam_tilt_deg": 1.5,
   "cam_dist_m": 0.144,
   "leaf_len_m": 0.163,
   "cover": 0.86,
   "render_s": 0.7,
   "seed": 525048596,
   "phone": {
    "exposure_gain": 0.53,
    "sat": 1.06,
    "rescale": 0.71,
    "noise": 0.0049,
    "jpeg_q": 64
   }
  }
 }
];
export const TRAIN = [
 {
  "id": "v0897_whole_0",
  "img": "leaf_train_0",
  "preset": "studio",
  "mode": "whole",
  "seed": 27140682,
  "w": 896,
  "h": 672
 },
 {
  "id": "v0897_closeup_1",
  "img": "leaf_train_1",
  "preset": "sun_wet",
  "mode": "closeup",
  "seed": 1989743324,
  "w": 256,
  "h": 256
 },
 {
  "id": "v0897_whole_2",
  "img": "leaf_train_2",
  "preset": "studio",
  "mode": "whole",
  "seed": 1871725414,
  "w": 1024,
  "h": 512
 }
];
export const COUNTS = {
 "texturesUsable": 1221,
 "texturesOfTrain": 1225,
 "setV1": 1353
};
export const SET1 = {
 "n": 1353,
 "rustFlags": "000000000000000000001000101100100000000000000000000000000000001111111111111111111111111111111111111111111111111011111111111111111111111111111111011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000001111110000000000000001001111001111000111100001000000000001001001001000100000011110001001100111100000000000000111001111110000111000011101000010101000001000000010000000010100001110111001110101110011001110000010000001001000000011000010001100010111000100000011100000010000000001110000000000000000000000000000000000000000000000000000000011100000001000100010010100100001110000000001000100000110000111010000110010100000110000000011101000000000000001000000000000000010000000101000000000000010000001000111111111111101111111011111111111111111111111111111111111111111111111101111111111110011111111111111111111111111111101111011111111111111111110111111111111111101111101111011101111111111111101110111111101011110111111111111111110010011101111011111110111111111111111111111111111111111001101111111110111111011001111101111111111111011111010111111110111111111011111111111111111110011111111111110101110111111101111111110111011110110111011110111101",
 "thisLeaf": [676, 677, 678]
};
